---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # fix backwards incompatibilities in template
    - name: Fix Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: fix

    # validate templates
    - name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: infra/packer/basic_ec2_amazonlinux.pkr.hcl

    # build artifact
    - name: Build Artifact
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort"
        target: infra/packer/basic_ec2_amazonlinux.pkr.hcl
      env:
        PACKER_LOG: 1