---

name: Packer

on:
  push:
    paths:
    - 'infra/packer/**'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # validate templates
    - name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: infra/packer/basic_ec2_amazonlinux.pkr.hcl

    # build artifact
    - name: Build Artifact
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort"
        target: infra/packer/basic_ec2_amazonlinux.pkr.hcl
      env:
        PACKER_LOG: 1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-north-1